### ISSUE TITLE
hourglass icon should have a tooltip explaining it is reading repos from github

### ISSUE THREAD

**Issue by erikh** [tinyci/ci-ui#32]
People are going to want to know this, so let's make it super obvious, at least the first time.

**Comment by invisiblehermit** [comment]
Gotta it, I will figure something out

**Comment by invisiblehermit** [comment]
Can I get a screenshot where it is

**Comment by erikh** [comment]
<img width="546" alt="Screen Shot 2019-04-17 at 1 03 01 AM" src="https://user-images.githubusercontent.com/18923/56271127-90b60480-60ac-11e9-98f8-7ed9a06072ff.png">
here, where the magnifying glass is -- it's replaced with the hourglass when the search is occurring.

**Comment by invisiblehermit** [comment]
As for how the search function works right now, I don't think we need the search icon at all. When users type something we can show this:

![Screen Shot 2019-04-18 at 4 54 57 PM](https://user-images.githubusercontent.com/15034049/56393803-0334fa80-61fb-11e9-9629-52f63f519f3f.png)

**Comment by erikh** [comment]
I like this, but let's make it shorter like "scanning" or something like
that. Small screens will thank us.
